use rclone instead of rsync for backupphoto

diff --git a/roles/backup/files/backupphoto b/roles/backup/files/backupphoto
--- a/roles/backup/files/backupphoto
+++ b/roles/backup/files/backupphoto
@@ -3,99 +3,60 @@
 help_msg() {
     cat << EOF
 Usage:
-  backupphoto target
+  backupphoto command
 
-With target:
-  all          Backup all the PhotoHub
-  fast         Backup only current year
-  <directory>  Backup only this directory 
+Available commands:
+  all       Backup all files
+  fast      Backup only current year
+  check     Reports files that don't match using checksum
+
+Backup are based on modification time & size. 
+Use 'check' to test file integrity.
+
+Warning: only files in subdirectories Photos & RAW are backed up
 EOF
 }
 
-##---------------##
-## Prerequisites ##
-##---------------##
-# PhotoHub source directories
-PHD_LIVE="$HOME/MyPhotoHub"
-PHD_ARCHIVE="/Volumes/HDD/MyPhotoHubArchive"
-PHD=("$PHD_LIVE" "$PHD_ARCHIVE")
-for d in "${PHD[@]}"
-do
-    if [ ! -d "$d" ]; then
-        echo "ERROR: source directory '$d' does not exists" 1>&2
-        exit 1
-    fi
-done
-
 # PhotoHub backup directory
-PHD_BACKUP="/Volumes/IcyBox/MyPhotoHubBackup"
-if [ ! -d "$PHD_BACKUP" ]; then
-    echo "ERROR: backup disk not found ($PHD_BACKUP)" 1>&2
+BKPDIR="/Volumes/IcyBox/MyPhotoHubBackup"
+if [ ! -d "$BKPDIR" ]; then
+    echo "ERROR: backup disk not found ($BKPDIR)" 1>&2
     exit 1
 fi
 
-# Only these subdirectories under PHD will be sync
-PHD_SUBDIR=("Phototèque" "RAW")
-
-# Rsync
-RSYNC="/opt/local/bin/rsync"
-if [ ! -x "$RSYNC" ]; then
-    echo "ERROR: $RSYNC executable not found" 1>&2
+# rclone
+RCLONE_BIN="/opt/local/bin/rclone"
+if [ ! -x "$RCLONE_BIN" ]; then
+    echo "ERROR: $RCLONE_BIN executable not found" 1>&2
     exit 1
 fi
+RCLONE="$RCLONE_BIN --quiet --exclude .DS_Store"
 
-##------------------##
-## Check parameters ##
-##------------------##
-if [ $# -eq 0 ]; then
-    echo "ERROR: missing target" 1>&2
-    help_msg
-    exit 1
-fi
-
-if [ $# -gt 1 ]; then
-    echo "ERROR: too many targets" 1>&2
+#-- Main --#
+if [ $# -ne 1 ]; then
+    echo "ERROR: invalid arguments" 1>&2
     help_msg
     exit 1
 fi
 
 case $1 in
     all)
-        target=""
+        $RCLONE sync "$HOME/MyPhotoHub/Photos"  "$BKPDIR/MyPhotoHub/Photos"
+        $RCLONE sync "$HOME/MyPhotoHub/RAW"     "$BKPDIR/MyPhotoHub/RAW"
+
+        $RCLONE sync "/Volumes/HDD/MyPhotoHubArchive/RAW" "$BKPDIR/MyPhotoHubArchive/RAW"
         ;;
-    fast)
-        target=$(date +%Y) 
+    fast)   
+        $RCLONE sync "$HOME/MyPhotoHub/Photos/$(date +%Y)" "$BKPDIR/MyPhotoHub/Photos/$(date +%Y)"
+        ;;
+    check)
+        $RCLONE check "$HOME/MyPhotoHub/Photos" "$BKPDIR/MyPhotoHub/Photos"
+        $RCLONE check "$HOME/MyPhotoHub/RAW"     "$BKPDIR/MyPhotoHub/RAW"
+
+        $RCLONE check "/Volumes/HDD/MyPhotoHubArchive/RAW" "$BKPDIR/MyPhotoHubArchive/RAW"
         ;;
     *)
-        target="$1"
+        help_msg
+        exit 1
         ;;
 esac
-
-##------##
-## Main ##
-##------##
-for d in "${PHD[@]}"
-do
-    for subd in "${PHD_SUBDIR[@]}"; do
-        SRC="$d/$subd/$target"
-        if [ -d "$SRC" ]; then
-            TGT="$PHD_BACKUP/$(basename $d)/$subd"
-            if [ ! -d "$TGT" ]; then
-                mkdir -p "$TGT"
-                if [ $? -ne 0 ]; then
-                    echo "ERROR: unable to create directory '$TGT'" 1>&2
-                    continue
-                fi
-            fi
-            echo "$SRC -> $TGT"
-            # rsync options: rlptgoD
-            #  -rptgo       = recursive, permissions, times, group, owner
-            #  --progress   = progress bar
-            #  -h           = use human readable format number
-            #  -cheksum     = skip based on checksum, not mod-time & size
-            #  --delete     = delete files from backup dir if no more exist in source
-            #  --stats      = show statistics
-            $RSYNC -rptgo -h --progress -cheksum --delete --stats "$SRC/" "$TGT/"
-        fi
-    done
-done
